version: '3.8'

services:
  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRES_IN=${JWT_ACCESS_TOKEN_EXPIRES_IN}
      - JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_MAX_FILE_SIZE=${LOG_MAX_FILE_SIZE}
    volumes:
      - ./logs:/app/logs
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        echo 'Waiting for postgres...' &&
        while ! nc -z postgres 5432; do
          sleep 1
        done &&
        echo 'PostgreSQL started' &&
        npx prisma db push --force-reset &&
        npm run start:dev
      "
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
