version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
